CountryDashboardSystem/Models/Country.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace CountryDashboardSystem.Models
{
    public partial class Country
    {
        public Guid CountryId { get; set; }
        public string CountryName { get; set; }
        public string IsoCode { get; set; }
    }
}

CountryDashboardSystem/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CountryDashboardSystem.Models;
using System.Data;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CountryDashboardSystem.Services;
using System.Text.Json;
using System.Xml;

namespace CountryDashboardSystem.Controllers
{
    public class CountryController : Controller
    {
        private readonly CountryDashboardContext _context;
        //private readonly ICountryService _countryService;   

        public CountryController(CountryDashboardContext context)
        {
            _context = context;  
        }

        // GET: Country
        public async Task<IActionResult> Index()
        {
            return View(await _context.Countries.Take(10).ToListAsync());            
        }
        //string Baseurl = "http://api.worldbank.org/v2/country";
        //public async Task<ActionResult> Index()
        //{
        //    List<TResult> EmpInfo = new List<TResult>();
        //    using (var client = new HttpClient())
        //    {
        //        //Passing service base url
        //        client.BaseAddress = new Uri(Baseurl);
        //        client.DefaultRequestHeaders.Clear();
        //        //Define request data format
        //        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        //        //Sending request to find web api REST service resource GetAllEmployees using HttpClient
        //        HttpResponseMessage Res = await client.GetAsync("http://api.worldbank.org/v2/country");               

        //        //Checking the response is successful or not which is sent using HttpClient
        //        if (Res.IsSuccessStatusCode)
        //        {
        //            //Storing the response details recieved from web api
        //           // var EmpResponse = Res.Content.ReadAsStringAsync().Result;
        //            //Deserializing the response recieved from web api and storing into the Employee list
        //            //EmpInfo = JsonConvert.DeserializeObject<List<TResult>>(EmpResponse);

        //            using (var reponseStream = await Res.Content.ReadAsStreamAsync())
        //            {                        
        //                var options = new JsonSerializerOptions
        //                {
        //                    PropertyNameCaseInsensitive = true,
        //                };
        //                EmpInfo = await System.Text.Json.JsonSerializer.DeserializeAsync<List<TResult>>(reponseStream, options);
        //            }
        //        }
        //        //returning the employee list to view
        //        return View(EmpInfo);
        //    }
        //}


        // GET: Country/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .FirstOrDefaultAsync(m => m.CountryId == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // GET: Country/Create
        public IActionResult Create()
        {
            return View();
        }

        
        // POST: Country/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountryId,CountryName,IsoCode")] Country country)
        {
            if (ModelState.IsValid)
            {
                if (CountryExists(country.IsoCode))
                {
                    
                }
                else
                {
                    country.CountryId = Guid.NewGuid();
                    _context.Add(country);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }                
            }
            return View(country);
        }

        // GET: Country/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Country/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CountryId,CountryName,IsoCode")] Country country)
        {
            if (id != country.CountryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.CountryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Country/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .FirstOrDefaultAsync(m => m.CountryId == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var country = await _context.Countries.FindAsync(id);
            _context.Countries.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(string isoCode)
        {
            return _context.Countries.Any(e => e.IsoCode == isoCode);
        }

        private bool CountryExists(Guid id)
        {
            return _context.Countries.Any(e => e.CountryId == id);
        }

    }
}

CountryDashboardSystem/Views/Country/Create.cshtml
@model CountryDashboardSystem.Models.Country

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CountryName" class="control-label"></label>
                <input asp-for="CountryName" class="form-control" />
                <span asp-validation-for="CountryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsoCode" class="control-label"></label>
                <input asp-for="IsoCode" class="form-control" />
                <span asp-validation-for="IsoCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CountryDashboardSystem/Views/Country/Delete.cshtml
@model CountryDashboardSystem.Models.Country

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsoCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsoCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CountryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CountryDashboardSystem/Views/Country/Details.cshtml
@model CountryDashboardSystem.Models.Country

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsoCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsoCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CountryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CountryDashboardSystem/Views/Country/Edit.cshtml
@model CountryDashboardSystem.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CountryId" />
            <div class="form-group">
                <label asp-for="CountryName" class="control-label"></label>
                <input asp-for="CountryName" class="form-control" />
                <span asp-validation-for="CountryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsoCode" class="control-label"></label>
                <input asp-for="IsoCode" class="form-control" />
                <span asp-validation-for="IsoCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CountryDashboardSystem/Views/Country/Index.cshtml
@model IEnumerable<CountryDashboardSystem.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Country Dashboard</h1>

<div class="row">
    <button class="btn-block" onclick="location.href='@Url.Action("Create", "Country")'">Add New Country</button>
</div>

<br/>

<div class="row">
    @foreach (var item in Model)
    { 
        <div class="card m-1" style="width:350px;">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(modelItem => item.CountryName)</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.IsoCode)</h6>
                <p class="card-text">
                    <a asp-action="Edit" asp-route-id="@item.CountryId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.CountryId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.CountryId">Delete</a>
                </p>                
            </div>
        </div>
    }
 </div>